(let ([x {record (price = 8) (other = #f)}])
  (case ((inl x) as ((Record (price = Integer) (other = Boolean)) + (Pair Integer Boolean)))
    of ((inl (lambda ((x1 : (Record (price = Integer) (other = Boolean))))
              (record-ref (x1 price))))
        as ((Record (price = Integer) (other = Boolean)) + (Pair Integer Boolean)))
    or ((inr (lambda ((x2 : (Pair Integer Boolean))) (x2 . 1)))
        as ((Record (price = Integer) (other = Boolean)) + (Pair Integer Boolean)))))